# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 19:26
from __future__ import unicode_literals

import api_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('google_id', models.CharField(blank=True, max_length=255)),
                ('dropbox_id', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(default='username', max_length=30, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=32)),
                ('goodle_token', models.CharField(blank=True, max_length=255)),
                ('dropbox_token', models.CharField(blank=True, max_length=255)),
                ('is_confirmed', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='account is activated')),
                ('is_admin', models.BooleanField(default=False, verbose_name='staff account')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
            managers=[
                ('objects', api_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='master', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(db_column='permission', on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.Permission')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='viewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'viewer',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(db_column='role', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.Role'),
        ),
    ]
